Adding UDP socket close functionality
smoltcp-rs/smoltcp pull request #482
Opened 2021-05-31 12:26 UTC by ryan-summers

This PR fixes #475 by adding a `close()` method to UDP sockets to unbind from the current endpoint.

2021-05-31 13:12 UTC, Dirbaio requested changes
Sounds reasonable!

What happens with the packets in rx_buffer/tx_buffer when the socket is closed and reopened (possibly with a different endpoint)? Should they be cleared?

2021-05-31 13:12 UTC, Dirbaio commented on src/socket/udp.rs
> +        self.endpoint = IpEndpoint::default();
This should wake rx_waker, tx_waker.

2021-05-31 16:07 UTC, ryan-summers commented
I've added a new `PacketBuffer::clear()` API to allow us to flush the RX/TX buffer of the socket when closing it. Good catch there.

2021-05-31 16:25 UTC, Dirbaio approved these changes
Very nice! Thanks :)

2021-06-09 14:05 UTC, Dirbaio approved these changes

2021-06-09 14:31 UTC, merged