Emit dns servers in DHCPv4 repr. Fixes #504
smoltcp-rs/smoltcp pull request #505
Opened 2021-06-23 18:20 UTC by theli-ua

2021-06-23 18:22 UTC, theli-ua commented
ok, no alloc, right, let me fix that

2021-06-23 19:17 UTC, Dirbaio requested changes

2021-06-23 19:17 UTC, Dirbaio commented on src/wire/dhcpv4.rs
> +            len += dns_servers.iter()
simpler to do `.iter().flatten().count() * 4`

2021-06-23 19:17 UTC, Dirbaio commented on src/wire/dhcpv4.rs
> +                            .copy_from_slice(ip.unwrap().as_bytes());
It's nice to avoid `unwrap`s if you can. You can get rid of this one if you do `dns_servers.iter().flatten()`

2021-06-23 19:17 UTC, Dirbaio commented on src/wire/dhcpv4.rs
> +                    }).last().unwrap_or(0);
returning `i+1` to then do `.last()` is a bit complex. You can return `()` and then do `.count()`.

2021-06-23 19:31 UTC, theli-ua commented
@Dirbaio I have a question re source formatting, it is a bit of a pain that one can't just do rustfmt. Is that intended?

2021-06-24 17:05 UTC, theli-ua commented
all clippy warnings are from code thats already there

2021-06-24 18:06 UTC, crawford commented
@theli-ua do you mind fixing the clippy warnings while you are in here? Regarding `rustfmt`, the maintainers have a preferred style that isn't easily expressible and have opted to format the code by hand.

2021-06-24 18:08 UTC, crawford commented on src/wire/dhcpv4.rs
> +                    .map(|(i, ip)| {
I believe you need to use inspect() instead.

2021-06-24 18:27 UTC, theli-ua commented
manual formatting seem to serves as unnecessary friction and deterrent for potential contributions  tbh.

I fixed clippy warnings, but really they were all over the place and have nothing to do with the change in this pr

2021-06-24 18:53 UTC, crawford commented
Hmm, that was a much larger fix than I expected. I only saw a single clippy error from https://github.com/smoltcp-rs/smoltcp/pull/505/commits/e023164908681e6ebce2a229bb5d7bca5e4ec735 (though, I realize now you mentioned warnings, not errors). I think you can probably drop that last commit from this PR.

2021-06-25 19:00 UTC, theli-ua commented
@crawford I've removed last commit and all checks are passing. Let me know if there is more feedback

2021-06-25 20:18 UTC, crawford commented
Overall, this seems fine to me (might want to squash the commit history in this PR though), but I’m not a maintainer so I must defer to @Dirbaio.

2021-06-27 06:42 UTC, Dirbaio approved these changes
Looks great, thank you!

2021-06-27 06:42 UTC, merged

2021-06-28 17:26 UTC, theli-ua commented
@Dirbaio what's the current approach for 0.7.x maintenance releases?

2021-06-28 17:28 UTC, Dirbaio commented
If you want, send a PR agains the `v0.7.x` branch cherry-picking this change, and I'll release it.

2021-06-28 17:35 UTC, theli-ua commented
@Dirbaio 0.7.x *is* the branch it was merged into :D

2021-06-28 17:38 UTC, Dirbaio commented
Oh! :rofl: 

Okay, let me release and cherry-pick into master.

2021-06-28 17:44 UTC, Dirbaio commented
v0.7.5 now out

2021-06-28 18:16 UTC, Dirbaio commented
@theli-ua next time send PRs to master, we later cherry-pick cherrypickable features back to `v0.7.x`, not the other way around.